lib: [
  "_build/install/default/lib/coqpilot/META"
  "_build/install/default/lib/coqpilot/dune-package"
  "_build/install/default/lib/coqpilot/opam"
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.a" {"tactics-plugin/coqpilot_client_plugin.a"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.cma" {"tactics-plugin/coqpilot_client_plugin.cma"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.cmi" {"tactics-plugin/coqpilot_client_plugin.cmi"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.cmt" {"tactics-plugin/coqpilot_client_plugin.cmt"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.cmx" {"tactics-plugin/coqpilot_client_plugin.cmx"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.cmxa" {"tactics-plugin/coqpilot_client_plugin.cmxa"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.ml" {"tactics-plugin/coqpilot_client_plugin.ml"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Coqpilot_tactics.cmi" {"tactics-plugin/coqpilot_client_plugin__Coqpilot_tactics.cmi"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Coqpilot_tactics.cmt" {"tactics-plugin/coqpilot_client_plugin__Coqpilot_tactics.cmt"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Coqpilot_tactics.cmx" {"tactics-plugin/coqpilot_client_plugin__Coqpilot_tactics.cmx"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Message.cmi" {"tactics-plugin/coqpilot_client_plugin__Message.cmi"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Message.cmt" {"tactics-plugin/coqpilot_client_plugin__Message.cmt"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Message.cmti" {"tactics-plugin/coqpilot_client_plugin__Message.cmti"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin__Message.cmx" {"tactics-plugin/coqpilot_client_plugin__Message.cmx"}
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_tactics.ml" {"tactics-plugin/coqpilot_tactics.ml"}
  "_build/install/default/lib/coqpilot/tactics-plugin/message.ml" {"tactics-plugin/message.ml"}
  "_build/install/default/lib/coqpilot/tactics-plugin/message.mli" {"tactics-plugin/message.mli"}
]
lib_root: [
  "_build/install/default/lib/coq/user-contrib/Coqpilot/Tactics.glob" {"coq/user-contrib/Coqpilot/Tactics.glob"}
  "_build/install/default/lib/coq/user-contrib/Coqpilot/Tactics.v" {"coq/user-contrib/Coqpilot/Tactics.v"}
  "_build/install/default/lib/coq/user-contrib/Coqpilot/Tactics.vo" {"coq/user-contrib/Coqpilot/Tactics.vo"}
  "_build/install/default/lib/coq/user-contrib/Coqpilot/coqpilot_client_plugin.cmxs" {"coq/user-contrib/Coqpilot/coqpilot_client_plugin.cmxs"}
]
libexec: [
  "_build/install/default/lib/coqpilot/tactics-plugin/coqpilot_client_plugin.cmxs" {"tactics-plugin/coqpilot_client_plugin.cmxs"}
]
